default: &default
  adapter: mysql2
  encoding: utf8
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: <%= ENV["DB_DEV"] %>

test:
  <<: *default
  database: <%= ENV["DB_TEST"] %>

production:
  <<: *default
  database: <%= ENV["DB_PROD"] %>
